flowchart TD
    A[startCustomerOnboarding]
    B[collectCustomerProfile]
    C[acceptCustomerTerms]
    D[setCustomerPhoneNumber]
    E[verifyCustomerPhoneNumber]
    F[setCustomerEmail]
    G[verifyCustomerEmail]
    H[setCustomerAddress]
    I[onboardCustomer]

    A --> B --> C --> D --> E --> F --> G --> H --> I
