flowchart TD
    A[startCustomerOnboarding]
    B[collectCustomerProfile]
    C[setCustomerPhoneNumber]
    D[verifyCustomerPhoneNumber]
    E[setCustomerAddress]
    F[acceptCustomerTerms]
    G[setCustomerEmail]
    H[verifyCustomerEmail]
    I[onboardCustomer]

    A --> B --> C --> D --> E --> F --> G --> H --> I
