flowchart TD
    A[startCustomerOnboarding]
    B[collectCustomerProfile]
    C[acceptCustomerTerms]
    D[setCustomerPhoneNumber]
    E[verifyCustomerPhoneNumber]
    F[setCustomerAddress]
    G[setCustomerEmail]
    H[verifyCustomerEmail]
    I[onboardCustomer]

    A --> B --> C --> D --> E --> F --> G --> H --> I
