flowchart TD

    OC[onboardCustomer]
    AT[acceptCustomerTerms]
    CP[collectCustomerProfile]
    SO[startCustomerOnboarding]
    VP[verifyCustomerPhoneNumber]
    SP[setCustomerPhoneNumber]
    VE[verifyCustomerEmail]
    SE[setCustomerEmail]
    SA[setCustomerAddress]

    OC -->|1| AT
    AT -->|2| CP
    CP -->|3| SO

    SO -->|4| CP
    CP -->|5| AT
    AT -->|6| OC

    OC -->|7| VP
    VP -->|8| SP
    SP -->|9| VP
    VP -->|10| OC

    OC -->|11| VE
    VE -->|12| SE
    SE -->|13| VE
    VE -->|14| OC

    OC -->|15| SA
    SA -->|16| OC
